<?php

namespace app\dyRun\command;

use app\common\model\Merchant;
use app\dyrun\service\PaymentService;
use think\console\Command;
use think\console\Input;
use think\console\Output;

class Payment extends Command
{
    protected function configure()
    {
        $this->setName('payment')->setDescription('测试上游支付接口闭环....zshx');
//        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(Input $input, Output $output)
    {
        $output->writeln("执行开始");

        $mch = Merchant::get(1); // 加载商户
        $service = new PaymentService($mch);
        // bool
        $service->createOrderIn(PaymentService::PAY_NAME_PAYHAYU, 'test' . rand(10000, 88888), 0.01, [
//            'mch_email' => '',  // 可选 String
//            'mch_name' => '',  // 可选 String
//            'mch_tel' => '', // 可选 String
//            'pay_type' => PayHaYuClient::TYPE_INR, // 暂仅支持 INR 印度
        ]);
//            $result = $service->getResult(); // array 上游接口调用结果
        $output->writeln("状态：" . $service->getStatus());
        $output->writeln("消息：" . $service->getMsg());
        $output->writeln("API消息：" . $service->getApiMsg());
        $output->writeln("API结果：" . json_encode($service->getResult(), JSON_UNESCAPED_UNICODE));

        $output->writeln("执行完成");
    }
}